export const feats = [
  {
    feat: "Complete Your First Workout",
    name: "Master Roshi's Apprentice ",
    description:
      "Just like Goku's first Kamehameha and Krillin's first death, you've just unleashed your fitness journey. Keep going!",
    state: false,
    date: "",
    level: 1,
    type: "Workouts Consistency",
    featValue: 1,
  },
  {
    feat: "Complete 5 Workouts",
    name: "Yamcha's Rising Spirit",
    description:
      "You're charging up like Vegeta - or at least Yamcha if we're being serious. Five down, a universe of strength to conquer!",
    state: false,
    date: "",
    level: 1,
    type: "Workouts Consistency",
    featValue: 5,
  },
  {
    feat: "Complete 10 Workouts",
    name: "Becoming A Threat",
    description:
      "Ten workouts? Your power level now is definitely over... 10. 15? Fine, 20. Frieza's watching!",
    state: false,
    date: "",
    level: 1,
    type: "Workouts Consistency",
    featValue: 10,
  },
  {
    feat: "Complete 25 Workouts",
    name: "There Is Hidden Power",
    description:
      "25 workouts! You're flying through this like Goku on his Nimbus Cloud. Congratulations and aim even higher!",
    state: false,
    date: "",
    level: 1,
    type: "Workouts Consistency",
    featValue: 25,
  },
  {
    feat: "Complete 50 Workouts",
    name: "Serious Training Starting",
    state: false,
    description:
      "50 workouts! Are you training to fight Cell? Because you're halfway to Super Saiyan strength! P.S: Not quite but keep going!",
    date: "",
    level: 2,
    type: "Workouts Consistency",
    featValue: 50,
  },
  {
    feat: "Complete 75 Workouts",
    name: "There Surely Is Hidden Power!",
    description:
      "75 workouts! There you go, you're showing more resilience than Gohan in the Hyperbolic Time Chamber.",
    state: false,
    date: "",
    level: 2,
    type: "Workouts Consistency",
    featValue: 75,
  },
  {
    feat: "Complete 100 Workouts",
    name: "Standing On Your Own!",
    description:
      "100 workouts! You're not just a Super Saiyan, actually you probably aren't. But keep going, you will get there!",
    state: false,
    date: "",
    level: 3,
    type: "Workouts Consistency",
    featValue: 100,
  },
  {
    feat: "Complete 250 Workouts",
    name: "Genki Dama",
    description:
      "250 workouts! You're outlasting Goku's Spirit Bomb prep time, and that says something! Amazing!",
    state: false,
    date: "",
    level: 4,
    type: "Workouts Consistency",
    featValue: 250,
  },
  {
    feat: "Complete 500 Workouts",
    name: "A New Form Unleashed!",
    description:
      "500 workouts! Make room everybody, make room so the Super Saiyan can enter!",
    state: false,
    date: "",
    level: 5,
    type: "Workouts Consistency",
    featValue: 500,
  },
  {
    feat: "Complete 750 Workouts",
    name: "Earth Enemies Should Stay Away!",
    description:
      "750 workouts, wow, you're not kidding! Earth surely has a new protector now, keep smashing it!",
    state: false,
    date: "",
    level: 6,
    type: "Workouts Consistency",
    featValue: 750,
  },
  {
    feat: "Complete 1,000 Workouts",
    name: "Shenron's Ultimate Wish",
    description:
      "1000 workouts! Look in the mirror and congratulate yourself, you've made it - and your hair is probably blonde.",
    state: false,
    date: "",
    level: 7,
    type: "Workouts Consistency",
    featValue: 1000,
  },

  {
    feat: "Complete 3 Workouts In A Week",
    name: "Piccolo's Special Training",
    state: false,
    description:
      "Three workouts in a week? You're training like Piccolo - consistent, disciplined and strong!",
    date: "",
    level: 1,
    type: "Workouts Streak",
    featValue: 3,
  },
  {
    feat: "Complete 4 Workouts In A Week",
    name: "Onto Finding Goku",
    description:
      "Four in a week? You're definitely channeling your inner Goku - motivated and powerful.",
    state: false,
    date: "",
    level: 2,
    type: "Workouts Streak",
    featValue: 4,
  },
  {
    feat: "Complete 5 Workouts In A Week",
    name: "Found Goku!",
    description:
      "Five workouts! All right, you're definitely on a Goku training spree. Keep flying high!",
    state: false,
    date: "",
    level: 3,
    type: "Workouts Streak",
    featValue: 5,
  },
  {
    feat: "Complete 6 Workouts In A Week",
    name: "Rivaling Vegeta",
    description:
      "Six in a week! You're training harder than Vegeta after Goku went Super Saiyan on Namek! Keep pushing!",
    state: false,
    date: "",
    level: 4,
    type: "Workouts Streak",
    featValue: 6,
  },
  {
    feat: "Complete 7 Workouts In A Week",
    name: "Week Of Destruction",
    description:
      "Seven in a week? You've matched the Dragon Balls! Grant your body its wish for strength - and some rest as well.",
    state: false,
    date: "",
    level: 5,
    type: "Workouts Streak",
    featValue: 7,
  },
  {
    feat: "Perform 100 Sets",
    name: "Yajirobe's Life Training",
    description: "100 sets! Congratulations for exceeding Yajirobe's record!",
    state: false,
    date: "",
    level: 1,
    type: "Sets",
    featValue: 100,
  },
  {
    feat: "Perform 500 Sets",
    name: "Turtle School Member",
    description:
      "500 sets! You could easily take on an army of Saibamen yourself, just ask Yamcha.",
    state: false,
    date: "",
    level: 2,
    type: "Sets",
    featValue: 500,
  },
  {
    feat: "Perform 1,000 Sets",
    name: "Could Maybe Do A Kamehameha!",
    description:
      "1,000 sets! You're creating energy waves stronger than a Kamehameha!",
    state: false,
    date: "",
    level: 3,
    type: "Sets",
    featValue: 1000,
  },
  {
    feat: "Perform 2,500 Sets",
    name: "Could Maybe Give Vegeta A Shot!",
    description:
      "2,500 sets! You must be prepping to spar with Vegeta. Keep building strenght!",
    state: false,
    date: "",
    level: 4,
    type: "Sets",
    featValue: 2500,
  },
  {
    feat: "Perform 5,000 Sets",
    name: "Yep, Could Ask Vegeta To Spar!",
    description:
      "5,000 sets! At this rate, Goku can just stay dead, the Earth has a new protector.",
    state: false,
    date: "",
    level: 5,
    type: "Sets",
    featValue: 5000,
  },
  {
    feat: "Perform 7,500 Sets",
    name: "Imperfect Cell",
    description: "7,500 sets! You could smack imperfect Cell and he'd call you",
    state: false,
    date: "",
    level: 6,
    type: "Sets",
    featValue: 7500,
  },
  {
    feat: "Perform 10,000 Sets",
    name: "Over 9000!",
    description:
      "10,000 sets - so basically over 9000! You've achieved a legendary milestone, Goku would be proud!",
    state: false,
    date: "",
    level: 7,
    type: "Sets",
    featValue: 10000,
  },
  {
    feat: "Perform 1,000 Reps",
    name: "Gohan's Spirit",
    description:
      "1,000 reps! You're building strength like a Saiyan building its Ki. Keep it up!",
    state: false,
    date: "",
    level: 1,
    type: "Reps",
    featValue: 1000,
  },
  {
    feat: "Perform 10,000 Reps",
    name: "New Buddy For Chiaotzu",
    description:
      "10,000 reps! Chiaotzu would hang out with you for sure, not so sure about Tien!",
    state: false,
    date: "",
    level: 2,
    type: "Reps",
    featValue: 10000,
  },
  {
    feat: "Perform 25,000 Reps",
    name: "Maybe A Namekian?",
    description:
      "25,000 reps! What are you, a Namekian with stretchy limbs? (it's a compliment, yes)",
    state: false,
    date: "",
    level: 3,
    type: "Reps",
    featValue: 25000,
  },

  {
    feat: "Perform 50,000 Reps",
    name: "Kaio-Ken Concentration",
    description:
      "50,000 reps! You're not just breaking limits, you're rewriting them.",
    state: false,
    date: "",
    level: 4,
    type: "Reps",
    featValue: 50000,
  },
  {
    feat: "Perform 75,000 Reps",
    name: "Could VS An Army",
    description:
      "75,000 reps! Are the androids attacking again?! If they do, they stand no chance.",
    state: false,
    date: "",
    level: 5,
    type: "Reps",
    featValue: 75000,
  },
  {
    feat: "Perform 100,000 Reps",
    name: "Vegeta's New Rival",
    description: "100,000 reps! Now Vegeta would be proud.",
    state: false,
    date: "",
    level: 7,
    type: "Reps",
    featValue: 100000,
  },

  {
    feat: "Lift ",
    name: "Krillin's Friend",
    description:
      "Krillin could definitely use a new buddy in the gym, I guess he found one now!",
    state: false,
    date: "",
    level: 1,
    type: "Volume",
    featValue: 100000,
  },
  {
    feat: "Lift ",
    name: "Can Try And Carry Yajirobe",
    description:
      "Let me call Yajirobe, he's tired of walking and asked if anyone could carry him!",
    state: false,
    date: "",
    level: 1,
    type: "Volume",
    featValue: 250000,
  },
  {
    feat: "Lift ",
    name: "King Kai's New Hope",
    description:
      "You've lifted enough to make King Kai gasp - and not due to a bad joke.",
    state: false,
    date: "",
    level: 1,
    type: "Volume",
    featValue: 500000,
  },
  {
    feat: "Lift ",
    name: "Could Lift Yajirobe's Mom",
    description: "Are you trying to lift Yajirobe's mom?",
    state: false,
    date: "",
    level: 1,
    type: "Volume",
    featValue: 750000,
  },
  {
    feat: "Lift ",
    name: "Could Lift Vegeta's Ego",
    description:
      "You've lifted more weight than Vegeta's ego now. Keep soaring and soon you'll lift his pride!",
    state: false,
    date: "",
    level: 2,
    type: "Volume",
    featValue: 1000000,
  },
  {
    feat: "Lift ",
    name: "Could Lift Oozaru Vegeta's Ego",
    description:
      "You now lifted more than Vegeta's ego weight in Great Ape form!",
    state: false,
    date: "",
    level: 3,
    type: "Volume",
    featValue: 1250000,
  },
  {
    feat: "Lift ",
    name: "Almost Out Of Weights!",
    description: "Hey, leave some weight for the other Earthlings too!",
    state: false,
    date: "",
    level: 3,
    type: "Volume",
    featValue: 1500000,
  },
  {
    feat: "Lift ",
    name: "Heavy Even For Shenron",
    description:
      "There are people who would use the Dragon Balls to wish to lift this weight!",
    state: false,
    date: "",
    level: 4,
    type: "Volume",
    featValue: 1750000,
  },
  {
    feat: "Lift ",
    name: "Could Lift Vegeta's Pride",
    description: "Yup, you've definitely lifted Vegeta's pride by now.",
    state: false,
    date: "",
    level: 5,
    type: "Volume",
    featValue: 2000000,
  },
  {
    feat: "Lift ",
    name: "Very Hyperbolic, Much Saiyan",
    description:
      "Goku pushed his limits in the Hyperbolic Time Chamber, you've lifted the Hyperbolic Time Chamber!",
    state: false,
    date: "",
    level: 5,
    type: "Volume",
    featValue: 2250000,
  },
  {
    feat: "Lift ",
    name: "Out Of Weights, Moving To Namek",
    description: "Quick, someone call Namek, we need more weights on Earth!",
    state: false,
    date: "",
    level: 6,
    type: "Volume",
    featValue: 2500000,
  },
  {
    feat: "Lift ",
    name: "Enough Weight To Crush Krillin",
    description:
      "Do. Not. Touch. Krillin. He will explode given your power. And in General. Just don't touch.",
    state: false,
    date: "",
    level: 6,
    type: "Volume",
    featValue: 2750000,
  },
  {
    feat: "Lift ",
    name: "Super Saiyan Gains",
    description:
      "Well, well, well, Goku just found his new sparing partner now! Don't tell Vegeta!",
    state: false,
    date: "",
    level: 7,
    type: "Volume",
    featValue: 3000000,
  },

  {
    feat: "Deadlift Your Bodyweight",
    name: "Unironically Mr. Satan",
    description:
      "Deadlifting yourself? It's like Mr. Satan claiming he beat Cell - unexpected but impressively bold!",
    state: false,
    date: "",
    level: 2,
    type: "Exercises - Deadlift",
    featValue: 1,
  },
  {
    feat: "Deadlift 1.5x Your Bodyweight",
    name: "Could Use Some New Clothes",
    description:
      "I'm sure Piccolo's weighted clothes weren't made of concrete, but yours could be!",
    state: false,
    date: "",
    level: 5,
    type: "Exercises - Deadlift",
    featValue: 1.5,
  },

  {
    feat: "Deadlift 2x Your Bodyweight",
    name: "Vegeta Approves.",
    description: "Vegeta nods in approval.",
    state: false,
    date: "",
    level: 7,
    type: "Exercises - Deadlift",
    featValue: 2,
  },
  {
    feat: "Bench Press 0.75x Your Bodyweight",
    name: "A New Saga Begins",
    description: "Congratulations, you're ready to start your own Saga!",
    state: false,
    date: "",
    level: 2,
    type: "Exercises - Bench Press",
    featValue: 0.75,
  },
  {
    feat: "Bench Press Your Bodyweight",
    name: "Oozaru Could Barely Do It",
    description:
      "Incredible, you benched your own weight and didn't have to user your Ape Form (because we know you use it for something else)!",
    state: false,
    date: "",
    level: 5,
    type: "Exercises - Bench Press",
    featValue: 1,
  },
  {
    feat: "Bench Press 1.25x Your Bodyweight",
    name: "Frieza's New Force Member",
    description:
      "Incredible strength, Frieza would recruit you in his Force team. He'd fail, you don't need him.",
    state: false,
    date: "",
    level: 7,
    type: "Exercises - Bench Press",
    featValue: 1.25,
  },
  {
    feat: "Squat 1x Your Bodyweight",
    name: "Thicker Than A Saiyan Armor",
    description:
      "Great! Make sure to give your measurements when ordering your new armor, so it fits that booty.",
    state: false,
    date: "",
    level: 2,
    type: "Exercises - Squat",
    featValue: 1,
  },
  {
    feat: "Squat 1.25x Your Bodyweight",
    name: "Android 18's Booty Bane",
    description: "That booty...Android 18 would be fuming jealous!",
    state: false,
    date: "",
    level: 5,
    type: "Exercises - Squat",
    featValue: 1.25,
  },
  {
    feat: "Squat 1.5x Your Bodyweight",
    name: "King Kai's Planet Size Booty",
    description:
      "Hey, you! Yes, you, go to King Kai's planet if this gets too easy!",
    state: false,
    date: "",
    level: 7,
    type: "Exercises - Squat",
    featValue: 1.5,
  },

  {
    feat: "Shoulder Press 0.5x Your Bodyweight",
    name: "Chasing Saiyan Power",
    description:
      "A Saiyan's power is determined by how big his shoulders are. And how spiky his hair is. Keep it up!",
    state: false,
    date: "",
    level: 2,
    type: "Exercises - Shoulder Press",
    featValue: 0.5,
  },
  {
    feat: "Shoulder Press 0.75x Your Bodyweight",
    name: "Size: Namekian Dragon Balls",
    description: "Wow, three quarters of your bodyweight! You're like Ginyu before the body switch - getting ready for a big transformation there!"!,
    state: false,
    date: "",
    level: 5,
    type: "Exercises - Shoulder Press",
    featValue: 0.75,
  },
  {
    feat: "Shoulder Press Your Bodyweight",
    name: "No Shoulder Pads Needed",
    description:
      "You've done it, Super Saiyan! Even if you tried to get a big enough armor, you wouldn't find one to fit those giant shoulders.",
    state: false,
    date: "",
    level: 7,
    type: "Exercises - Shoulder Press",
    featValue: 1,
  },

  {
    feat: "Perform 1 Pull Up",
    name: "Earthling Girl's Challenge",
    state: false,
    description:
      "Amazing job, be proud! Every journey starts with the first one, and even Goku knows it!",
    date: "",
    level: 2,
    type: "Exercises - Pull Up",
    featValue: 1,
  },
  {
    feat: "Perform 8 Consecutive Pull Ups",
    name: "Not Obeying Gravity Laws",
    description:
      "Quick, someone tell Dr. Brief we need a new gravity machine for this Saiyan here!",
    state: false,
    date: "",
    level: 3,
    type: "Exercises - Pull Up",
    featValue: 8,
  },
  {
    feat: "Perform 12 Consecutive Pull Ups",
    name: "Can Probably Fly If Tried",
    description:
      "Tell Dr. Brief to scrap the previous one, we need a new, different and improved one!",
    state: false,
    date: "",
    level: 5,
    type: "Exercises - Pull Up",
    featValue: 12,
  },
  {
    feat: "Perform 18 Consecutive Pull Ups",
    name: "Climbing The Kirin Tower",
    description:
      "You're scaling your pull ups like Goku climbing the Korin Tower!",
    state: false,
    date: "",
    level: 6,
    type: "Exercises - Pull Up",
    featValue: 18,
  },
  {
    feat: "Perform 24 Consecutive Pull Ups",
    name: "Frieza Slapper",
    description:
      "Now go slap Frieza, he'll take it without budging as he has no other option.",
    state: false,
    date: "",
    level: 7,
    type: "Exercises - Pull Up",
    featValue: 24,
  },
  {
    feat: "Perform 1 Push Up",
    name: "Following Goku's Steps",
    description:
      "Congratulations for your first push up! You didn't even need to dodge, like Gohan with Piccolo!",
    state: false,
    date: "",
    level: 1,
    type: "Exercises - Push Up",
    featValue: 1,
  },
  {
    feat: "Perform 10 Consecutive Push Ups",
    name: "No More Background Character",
    description: "Ten push ups? You're definitely not slacking like Yajirobe!",
    state: false,
    date: "",
    level: 2,
    type: "Exercises - Push Up",
    featValue: 10,
  },
  {
    feat: "Perform 20 Consecutive Push Ups",
    name: "Friend With Mr. Popo",
    description:
      "Twenty in a row? Did you sneak into the Hyperbolic Time Chamber without telling?!",
    state: false,
    date: "",
    level: 3,
    type: "Exercises - Push Up",
    featValue: 20,
  },
  {
    feat: "Perform 30 Consecutive Push Ups",
    name: "Saiyan From The Top To Bottom",
    description: "Thirty push ups? Someone knows its focus!",
    state: false,
    date: "",
    level: 5,
    type: "Exercises - Push Up",
    featValue: 30,
  },
  {
    feat: "Perform 40 Consecutive Push Ups",
    name: "Catching Vegeta's Eye",
    description: "Forty push ups? That's a bigger chest than Bulma's!",
    state: false,
    date: "",
    level: 6,
    type: "Exercises - Push Up",
    featValue: 40,
  },
  {
    feat: "Perform 50 Consecutive Push Ups",
    name: "No Weak Link In A Super Saiyan",
    description:
      "Fifty push ups? Being a Super Saiyan comes with its perks, doesn't it?",
    state: false,
    date: "",
    level: 7,
    type: "Exercises - Push Up",
    featValue: 50,
  },
  {
    feat: "Hold A Plank For 1 Minute",
    name: "Yamcha's Stay Still Challenge",
    description: "Holding strong like Yamcha's in his stance, nice.",
    state: false,
    date: "",
    level: 1,
    type: "Exercises - Plank",
    featValue: 60,
  },
  {
    feat: "Hold A Plank For 2 Minutes",
    name: "Wish To Nap Like Piccolo",
    description:
      "Two minutes in plank? That's like Piccolo meditating before a big fight.",
    state: false,
    date: "",
    level: 2,
    type: "Exercises - Plank",
    featValue: 120,
  },

  {
    feat: "Hold A Plank For 5 Minutes",
    name: "Breaking Krillin's Record",
    description: "Five minutes in a plank? Krillin died five times, well done!",
    state: false,
    date: "",
    level: 3,
    type: "Exercises - Plank",
    featValue: 300,
  },
  {
    feat: "Hold A Plank For 10 Minutes",
    name: "SSSJ - Shreded Super Saiyajin",
    description:
      "Ten minutes in plank? You could shred some cheese on those abs! Super Saiyan cheese!",
    state: false,
    date: "",
    level: 5,
    type: "Exercises - Plank",
    featValue: 600,
  },
  {
    feat: "Perform 10 Different Exercises",
    name: "Broke Krillin's Record",
    description:
      "Good job, you've finally performed something more times than Krillin died.",
    state: false,
    date: "",
    level: 2,
    type: "Exercises",
    featValue: 10,
  },

  {
    feat: "Perform 25 Different Exercises",
    name: "Kamehameha Is Next",
    description:
      "That's a good repertoire of exercises, next learn the Kamehameha.",
    state: false,
    date: "",
    level: 5,
    type: "Exercises",
    featValue: 25,
  },

  {
    feat: "Perform 50 Different Exercises",
    name: "More Varied Than Goku's Menu",
    description:
      "Conquering 50 exercises? You're the ultimate fitness warrior, tackling a workout menu more varied than Goku's post-training feast!",
    state: false,
    date: "",
    level: 7,
    type: "Exercises",
    featValue: 50,
  },
  {
    feat: "Perform 10 Consecutive Sit-ups/Crunches",
    name: "EZ PZ, Goku's Rice Is Nice & Breezy",
    description:
      "Ten sit-ups in a row? You're crunching it like Goku crunches on a bowl of rice - always hungry for more!",
    state: false,
    date: "",
    level: 1,
    type: "Exercises - Sit-Ups/Crunches",
    featValue: 1,
  },
  {
    feat: "Perform 50 Consecutive Sit-ups/Crunches",
    name: "Joining The Ginyu Force",
    description:
      "Amazing, you're knocking out sit-ups like the Ginyu Force knocks out poses - with style, flair and a lot of strength!",
    state: false,
    date: "",
    level: 4,
    type: "Exercises - Sit-Ups/Crunches",
    featValue: 50,
  },
  {
    feat: "Perform 100 Consecutive Sit-ups/Crunches",
    name: "Yes, Throw Me A Senzu Bean",
    description: "100?! OK, you surely need a a Senzu Bean after this one!",
    state: false,
    date: "",
    level: 7,
    type: "Exercises - Sit-Ups/Crunches",
    featValue: 100,
  },
  {
    feat: "Perform 25 Consecutive Burpees",
    name: "Faster Pain Than Burter",
    description:
      "If Burter is the fastest in the universe, you probably have the fastest pulse right now!",
    state: false,
    date: "",
    level: 1,
    type: "Exercises - Burpees",
    featValue: 25,
  },
  {
    feat: "Perform 50 Consecutive Burpees",
    name: "Yamcha Killer",
    description: "Fifty burpees?! This would have killed Yamcha for sure.",
    state: false,
    date: "",
    level: 3,
    type: "Exercises - Burpees",
    featValue: 50,
  },
  {
    feat: "Perform 75 Consecutive Burpees",
    name: "Takes Pain Like A Saiyan",
    description:
      "Seventy-five burpees? There's blood going through those veins. Saiyan Blood.",
    state: false,
    date: "",
    level: 5,
    type: "Exercises - Burpees",
    featValue: 75,
  },
  {
    feat: "Perform 100 Consecutive Burpees",
    name: "Wouldn't Wish This On Anyone",
    description:
      "Avoiding doing 100 burpees is something to use a Dragon Balls wish on.",
    state: false,
    date: "",
    level: 7,
    type: "Exercises - Burpees",
    featValue: 100,
  },

  {
    feat: "Perform 10 Consecutive Hanging Leg Raises",
    name: "Nimbus Rider",
    description:
      "10 hanging leg raises? You're defying gravity like Goku on his first Nimbus ride - a bit shaky but soaring high!",
    state: false,
    date: "",
    level: 1,
    type: "Exercises - Hanging Leg Raises",
    featValue: 10,
  },
  {
    feat: "Perform 25 Consecutive Hanging Leg Raises",
    name: "Every Part (Abs) Is Important",
    description:
      "If you won't become a Super Saiyan yourself, your abs surely will!",
    state: false,
    date: "",
    level: 3,
    type: "Exercises - Hanging Leg Raises",
    featValue: 25,
  },
  {
    feat: "Perform 50 Consecutive Hanging Leg Raises",
    name: "Ginyu's Graceful Grasp",
    description:
      "You're showing off a core strength that rivals Captain Ginyu's balancing during his dance pose!",
    state: false,
    date: "",
    level: 5,
    type: "Exercises - Hanging Leg Raises",
    featValue: 50,
  },
  {
    feat: "Perform 1 Chin Up",
    name: "Saiyan In Progress",
    description:
      "If there's a way to start your journey to becoming a Super Saiyan, this is the one!",
    state: false,
    date: "",
    level: 1,
    type: "Exercises - Chin Up",
    featValue: 1,
  },
  {
    feat: "Perform 6 Consecutive Chin Ups",
    name: "Yajirobe Could Never",
    description:
      "Six chin ups? If you reeeally think this is too easy you can always tie Yajirobe to yourself.",
    state: false,
    date: "",
    level: 3,
    type: "Exercises - Chin Up",
    featValue: 6,
  },
  {
    feat: "Perform 14 Consecutive Chin Ups",
    name: "Like Vegeta's Tantrum",
    description:
      "You're hitting 14 chin-ups like Vegeta hits a temper tantrum - intense, fierce, and surprisingly effective!",
    state: false,
    date: "",
    level: 5,
    type: "Exercises - Chin Up",
    featValue: 14,
  },
  {
    feat: "Perform 24 Consecutive Chin Ups",
    name: "Super Saiyan Is Just The Start",
    description:
      "Twenty-four chin-ups? That's like Frieza revealing his final form - unexpected, awe-inspiring, and really a game-changer!",
    state: false,
    date: "",
    level: 7,
    type: "Exercises - Chin Up",
    featValue: 24,
  },
];
