const preselectedExercises = [
  {
    category: "Shoulders",
    name: "Arnold Dumbbell Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Behind The Neck Barbell Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Cable Face Pull",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Dumbbell Overhead Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Front Dumbbell Raise",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Hammer Strength Shoulder Press",
    measurement: ["weight", "reps"],
  },
  { category: "Shoulders", name: "High Pull", measurement: ["weight", "reps"] },
  {
    category: "Shoulders",
    name: "Kneeled Shoulder Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Lateral Dumbbell Raise",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Lateral Machine Raise",
    measurement: ["weight", "reps"],
  },
  { category: "Shoulders", name: "Log Press", measurement: ["weight", "reps"] },
  {
    category: "Shoulders",
    name: "One-Arm Standing Dumbbell Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Overhead Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Push Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Rear Delt Dumbbell Raise",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Rear Delt Machine Fly",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Seated Dumbbell Lateral Raise",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Seated Dumbbell Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Smith Machine Overhead Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Shoulders",
    name: "Standing Shoulders Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Triceps",
    name: "Cable Overhead Triceps Extension",
    measurement: ["weight", "reps"],
  },
  {
    category: "Triceps",
    name: "Close Grip Barbell Bench Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Triceps",
    name: "Dumbbell Overhead Triceps Extension",
    measurement: ["weight", "reps"],
  },
  {
    category: "Triceps",
    name: "EZ-Bar Skullcrusher",
    measurement: ["weight", "reps"],
  },
  {
    category: "Triceps",
    name: "Incline Bench Triceps Push",
    measurement: ["weight", "reps"],
  },
  {
    category: "Triceps",
    name: "Lying Triceps Extension",
    measurement: ["weight", "reps"],
  },
  {
    category: "Triceps",
    name: "Overhead Barbell Extension",
    measurement: ["weight", "reps"],
  },
  {
    category: "Triceps",
    name: "Parallel Bar Triceps Dip",
    measurement: ["weight", "reps"],
  },
  { category: "Triceps", name: "Ring Dip", measurement: ["weight", "reps"] },
  {
    category: "Triceps",
    name: "Rope Push Down",
    measurement: ["weight", "reps"],
  },
  {
    category: "Triceps",
    name: "Smith Machine Close Grip Bench Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Triceps",
    name: "V-Bar Push Down",
    measurement: ["weight", "reps"],
  },
  { category: "Biceps", name: "Barbell Curl", measurement: ["weight", "reps"] },
  {
    category: "Biceps",
    name: "Barbell Preacher Curl",
    measurement: ["weight", "reps"],
  },
  {
    category: "Biceps",
    name: "Barbell Cable Curl",
    measurement: ["weight", "reps"],
  },
  {
    category: "Biceps",
    name: "Dumbbell Concentration Curl",
    measurement: ["weight", "reps"],
  },
  {
    category: "Biceps",
    name: "Dumbbell Curl",
    measurement: ["weight", "reps"],
  },
  {
    category: "Biceps",
    name: "Dumbbell Hammer Curl",
    measurement: ["weight", "reps"],
  },
  {
    category: "Biceps",
    name: "Dumbbell Preacher Curl",
    measurement: ["weight", "reps"],
  },
  { category: "Biceps", name: "EZ-Bar Curl", measurement: ["weight", "reps"] },
  {
    category: "Biceps",
    name: "EZ-Bar Preacher Curl",
    measurement: ["weight", "reps"],
  },
  {
    category: "Biceps",
    name: "Seated Incline Dumbbell Curl",
    measurement: ["weight", "reps"],
  },
  {
    category: "Biceps",
    name: "Seated Machine Curl",
    measurement: ["weight", "reps"],
  },
  { category: "Chest", name: "Bar Push Ups", measurement: ["weight", "reps"] },
  {
    category: "Chest",
    name: "Barbell Floor Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Cable Crossover",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Chest Push Machine",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Chest Push Rubber Band Machine",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Close Grip Bench Pin Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Decline Barbell Bench Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Decline Hammer Strength Chest Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Diamond Push Up",
    measurement: ["weight", "reps"],
  },
  { category: "Chest", name: "Dips", measurement: ["weight", "reps"] },
  {
    category: "Chest",
    name: "Dumbbell Upper Flies",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Dumbbell Floor Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Eccentric Floor Chest Fly",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Flat Dumbbell Fly",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Floor Barbell Pinch Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Flat Barbell Bench Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Incline Barbell Bench Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Incline Dumbbell Fly",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Incline Hammer Strength Chest Press",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Incline Plate Chest Press",
    measurement: ["weight", "reps"],
  },
  { category: "Chest", name: "Punch Push Up", measurement: ["weight", "reps"] },
  { category: "Chest", name: "Push Up", measurement: ["weight", "reps"] },
  {
    category: "Chest",
    name: "Seated Machine Fly",
    measurement: ["weight", "reps"],
  },
  {
    category: "Chest",
    name: "Single Arm Cable Chest Fly",
    measurement: ["weight", "reps"],
  },
  { category: "Back", name: "Barbell Row", measurement: ["weight", "reps"] },
  { category: "Back", name: "Barbell Shrug", measurement: ["weight", "reps"] },
  { category: "Back", name: "Chin Up", measurement: ["weight", "reps"] },
  {
    category: "Back",
    name: "Close Grip Pull Up",
    measurement: ["weight", "reps"],
  },
  {
    category: "Back",
    name: "Dumbbell Dead Row",
    measurement: ["weight", "reps"],
  },
  { category: "Back", name: "Dumbbell Row", measurement: ["weight", "reps"] },
  { category: "Back", name: "Good Morning", measurement: ["weight", "reps"] },
  {
    category: "Back",
    name: "Hammer Strength Row",
    measurement: ["weight", "reps"],
  },
  {
    category: "Back",
    name: "Inverted Horizontal Ring Rows",
    measurement: ["weight", "reps"],
  },
  { category: "Back", name: "Lat Pulldown", measurement: ["weight", "reps"] },
  { category: "Back", name: "Machine Shrug", measurement: ["weight", "reps"] },
  {
    category: "Back",
    name: "Negative Pull Up",
    measurement: ["weight", "reps"],
  },
  {
    category: "Back",
    name: "Neutral Chin Up",
    measurement: ["weight", "reps"],
  },
  { category: "Back", name: "Pendlay Row", measurement: ["weight", "reps"] },
  { category: "Back", name: "Pull Up", measurement: ["weight", "reps"] },
  { category: "Back", name: "Rack Pull", measurement: ["weight", "reps"] },
  { category: "Back", name: "Row Machine", measurement: ["weight", "reps"] },
  {
    category: "Back",
    name: "Seated Cable Row",
    measurement: ["weight", "reps"],
  },
  {
    category: "Back",
    name: "Straight-Arm Cable Pushdown",
    measurement: ["weight", "reps"],
  },
  { category: "Back", name: "T-Bar Row", measurement: ["weight", "reps"] },
  {
    category: "Back",
    name: "T-Bar Row Machine",
    measurement: ["weight", "reps"],
  },
  {
    category: "Back",
    name: "Wide Grip Pull Down",
    measurement: ["weight", "reps"],
  },
  {
    category: "Legs",
    name: "Barbell Box Squat",
    measurement: ["weight", "reps"],
  },
  {
    category: "Legs",
    name: "Barbell Calf Raise",
    measurement: ["weight", "reps"],
  },
  {
    category: "Legs",
    name: "Barbell Front Squat",
    measurement: ["weight", "reps"],
  },
  {
    category: "Legs",
    name: "Barbell Glute Bridge",
    measurement: ["weight", "reps"],
  },
  { category: "Legs", name: "Barbell Squat", measurement: ["weight", "reps"] },
  {
    category: "Legs",
    name: "Beginner Shrimp Squat",
    measurement: ["weight", "reps"],
  },
  { category: "Legs", name: "Deadlift", measurement: ["weight", "reps"] },
  {
    category: "Legs",
    name: "Donkey Calf Raise",
    measurement: ["weight", "reps"],
  },
  { category: "Legs", name: "Farmer's Walk", measurement: ["weight", "reps"] },
  {
    category: "Legs",
    name: "Glute-Ham Raise",
    measurement: ["weight", "reps"],
  },
  {
    category: "Legs",
    name: "Leg Extension Machine",
    measurement: ["weight", "reps"],
  },
  { category: "Legs", name: "Leg Press", measurement: ["weight", "reps"] },
  {
    category: "Legs",
    name: "Lying Leg Curl Machine",
    measurement: ["weight", "reps"],
  },
  { category: "Legs", name: "Nordic Curls", measurement: ["weight", "reps"] },
  {
    category: "Legs",
    name: "Reverse Hyperextension",
    measurement: ["weight", "reps"],
  },
  {
    category: "Legs",
    name: "Romanian Deadlift",
    measurement: ["weight", "reps"],
  },
  {
    category: "Legs",
    name: "Seated Calf Raise Machine",
    measurement: ["weight", "reps"],
  },
  {
    category: "Legs",
    name: "Seated Leg Curl Machine",
    measurement: ["weight", "reps"],
  },
  {
    category: "Legs",
    name: "Standing Calf Raise Machine",
    measurement: ["weight", "reps"],
  },
  {
    category: "Legs",
    name: "Stiff-Legged Deadlift",
    measurement: ["weight", "reps"],
  },
  { category: "Legs", name: "Sumo Deadlift", measurement: ["weight", "reps"] },
  {
    category: "Legs",
    name: "Trap Bar Deadlift",
    measurement: ["weight", "reps"],
  },
  {
    category: "Abs",
    name: "Ab-Wheel Rollout",
    measurement: ["weight", "reps"],
  },
  { category: "Abs", name: "Cable Crunch", measurement: ["weight", "reps"] },
  { category: "Abs", name: "Crunch", measurement: ["weight", "reps"] },
  { category: "Abs", name: "Crunch Machine", measurement: ["weight", "reps"] },
  { category: "Abs", name: "Decline Crunch", measurement: ["weight", "reps"] },
  { category: "Abs", name: "Dragon Flag", measurement: ["weight", "reps"] },
  {
    category: "Abs",
    name: "Hanging Knee Raise",
    measurement: ["weight", "reps"],
  },
  {
    category: "Abs",
    name: "Hanging Leg Raise",
    measurement: ["weight", "reps"],
  },
  { category: "Abs", name: "Plank", measurement: ["weight", "reps"] },
  { category: "Abs", name: "Side Plank", measurement: ["weight", "reps"] },
  {
    category: "Abs",
    name: "Standing Cable Crunch",
    measurement: ["distance", "time"],
  },
  { category: "Cardio", name: "Cycling", measurement: ["distance", "time"] },
  {
    category: "Cardio",
    name: "Elyptical Trainer",
    measurement: ["distance", "time"],
  },
  {
    category: "Cardio",
    name: "Rowing Machine",
    measurement: ["distance", "time"],
  },
  {
    category: "Cardio",
    name: "Running (Outdoor)",
    measurement: ["distance", "time"],
  },
  {
    category: "Cardio",
    name: "Running (Treadmill)",
    measurement: ["distance", "time"],
  },
  {
    category: "Cardio",
    name: "Stationary Bike",
    measurement: ["distance", "time"],
  },
  { category: "Cardio", name: "Swimming", measurement: ["distance", "time"] },
  { category: "Cardio", name: "Walking", measurement: ["distance", "time"] },
  {
    category: "Corrective",
    name: "Double Hand Scapula Stretch",
    measurement: ["weight", "reps"],
  },
  {
    category: "Corrective",
    name: "Look Down Shoulder Stretch",
    measurement: ["weight", "reps"],
  },
  {
    category: "Corrective",
    name: "Push Up Plus",
    measurement: ["weight", "reps"],
  },
  {
    category: "Corrective",
    name: "Serreatus Plus Push Ups",
    measurement: ["weight", "reps"],
  },
  {
    category: "Corrective",
    name: "Single Lat Stretch",
    measurement: ["weight", "reps"],
  },
  {
    category: "Corrective",
    name: "Wall Screw Stretch",
    measurement: ["weight", "reps"],
  },
  {
    category: "Corrective",
    name: "Wrist Shoulder Dead Hang",
    measurement: ["weight", "reps"],
  },
];

export default preselectedExercises;
